#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
#
# Generate a broad known-answer-test corpus for the SHA-2 toolkit using Python's
# reference implementations (hashlib/hmac). The output is a committed C++ header
# so the test suite is fully reproducible and needs no runtime dependency on
# Python or OpenSSL. Re-run after changing the corpus:
#
#     python3 tests/vectors/generate_kat.py > tests/vectors/sha256_kat.hpp
#
# Determinism: inputs are produced by a fixed linear congruential generator, so
# the corpus is byte-for-byte stable across machines and Python versions.

import hashlib
import hmac
import sys


def lcg_bytes(seed, n):
    out = bytearray()
    x = seed & 0xFFFFFFFFFFFFFFFF
    while len(out) < n:
        x = (6364136223846793005 * x + 1442695040888963407) & 0xFFFFFFFFFFFFFFFF
        out.append((x >> 33) & 0xFF)
    return bytes(out)


def cpp_bytes(b):
    return "{" + ",".join("0x%02x" % c for c in b) + "}" if b else "{}"


def main():
    # Message lengths chosen to straddle every padding boundary up to a few
    # blocks, plus a couple of larger inputs.
    lengths = list(range(0, 135)) + [191, 192, 193, 255, 256, 257, 1000, 4096]

    hash_cases = []
    for i, n in enumerate(lengths):
        msg = lcg_bytes(0x1234_5678_9abc_def0 + i, n)
        hash_cases.append((msg,
                           hashlib.sha256(msg).hexdigest(),
                           hashlib.sha224(msg).hexdigest()))

    hmac_cases = []
    for i in range(40):
        klen = (i * 7 + 1) % 200
        mlen = (i * 13 + 3) % 300
        key = lcg_bytes(0xaaaa_0000 + i, klen)
        msg = lcg_bytes(0xbbbb_0000 + i, mlen)
        hmac_cases.append((key, msg, hmac.new(key, msg, hashlib.sha256).hexdigest()))

    out = sys.stdout
    out.write("// SPDX-License-Identifier: MIT\n")
    out.write("// AUTO-GENERATED by tests/vectors/generate_kat.py — do not edit by hand.\n")
    out.write("// Reference digests produced by Python hashlib/hmac.\n\n")
    out.write("#ifndef SHA2_TESTS_SHA256_KAT_HPP\n#define SHA2_TESTS_SHA256_KAT_HPP\n\n")
    out.write("#include <cstdint>\n#include <vector>\n\nnamespace kat {\n\n")

    out.write("struct HashVector { std::vector<std::uint8_t> msg; const char* sha256; const char* sha224; };\n")
    out.write("struct HmacVector { std::vector<std::uint8_t> key; std::vector<std::uint8_t> msg; const char* mac; };\n\n")

    out.write("inline const std::vector<HashVector>& hash_vectors() {\n")
    out.write("    static const std::vector<HashVector> v = {\n")
    for msg, s256, s224 in hash_cases:
        out.write('        {%s, "%s", "%s"},\n' % (cpp_bytes(msg), s256, s224))
    out.write("    };\n    return v;\n}\n\n")

    out.write("inline const std::vector<HmacVector>& hmac_vectors() {\n")
    out.write("    static const std::vector<HmacVector> v = {\n")
    for key, msg, mac in hmac_cases:
        out.write('        {%s, %s, "%s"},\n' % (cpp_bytes(key), cpp_bytes(msg), mac))
    out.write("    };\n    return v;\n}\n\n")

    out.write("}  // namespace kat\n\n#endif  // SHA2_TESTS_SHA256_KAT_HPP\n")


if __name__ == "__main__":
    main()
